# Generated by Django 4.2.7 on 2025-11-20 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_lider', models.CharField(max_length=100)),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NormaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="e.g., '8.3'", max_length=50, unique=True)),
                ('titulo', models.CharField(help_text="e.g., 'Design and development of products and services'", max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="e.g., 'Code Review', 'Deployment'", max_length=100, unique=True)),
                ('responsable', models.CharField(help_text='Person or role responsible', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NC_MAYOR', 'No Conformidad Mayor'), ('NC_MENOR', 'No Conformidad Menor'), ('OBSERVACION', 'Observación'), ('OPORTUNIDAD', 'Oportunidad de Mejora')], max_length=20)),
                ('descripcion', models.TextField()),
                ('evidencia_objetiva', models.TextField(help_text='Description of the evidence found')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='auditorias.auditoria')),
                ('norma_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.normareferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('descripcion', models.CharField(max_length=255)),
                ('url_externa', models.URLField(blank=True, help_text='Link to external system (e.g., Jira, GitHub)', null=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='auditorias.hallazgo')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='normas',
            field=models.ManyToManyField(related_name='auditorias', to='auditorias.normareferencia'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='auditorias.planauditoria'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.procesosoftware'),
        ),
    ]
